-- The partner bucket, which existed as a constant and was never used.
--
-- `bucket_of` consulted only PLATFORM_BUCKETS, so Ownify registrations — a
-- partner's own population, already excluded from the acquisition goal by
-- `is_organic` — were displayed as `other`. The funnel's own comment says a
-- bucket that hides what it swallowed is worse than no bucket, and `other` was
-- hiding the one origin we can name exactly.
--
-- Generated by app.funnel.build_bucket_function_sql(); tests/test_funnel.py
-- asserts this file still matches it.

CREATE OR REPLACE FUNCTION funnel_platform_bucket(p text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT CASE lower(trim(coalesce(p, '')))
        WHEN 'ownify' THEN 'partner'
        WHEN 'clawhub' THEN 'clawhub'
        WHEN 'hermes' THEN 'hermes'
        WHEN 'smithery' THEN 'smithery'
        WHEN 'glama' THEN 'glama'
        WHEN 'a2a' THEN 'a2a'
        WHEN 'erc8004' THEN 'erc8004'
        WHEN 'erc-8004' THEN 'erc8004'
        WHEN 'rnwy' THEN 'rnwy'
        WHEN 'virtuals-acp' THEN 'virtuals-acp'
        WHEN 'virtuals' THEN 'virtuals-acp'
        WHEN 'virtuals_acp' THEN 'virtuals-acp'
        WHEN 'olas' THEN 'olas'
        WHEN 'taskmarket' THEN 'taskmarket'
        WHEN 'x402-bazaar' THEN 'x402-bazaar'
        WHEN 'x402bazaar' THEN 'x402-bazaar'
        WHEN 'bazaar' THEN 'x402-bazaar'
        WHEN 'langchain' THEN 'langchain'
        WHEN 'moltrust-langchain' THEN 'langchain'
        WHEN 'crewai' THEN 'crewai'
        WHEN 'moltrust-crewai' THEN 'crewai'
        WHEN 'openai-agents' THEN 'openai-agents'
        WHEN 'openai_agents' THEN 'openai-agents'
        WHEN 'vercel-ai' THEN 'vercel-ai'
        WHEN 'vercel' THEN 'vercel-ai'
        WHEN 'ai-sdk' THEN 'vercel-ai'
        WHEN 'sdk' THEN 'sdk'
        WHEN 'gate' THEN 'gate'
        WHEN 'moltrust-gate' THEN 'gate'
        ELSE 'other'
    END
$$;
