-- 014: subscription lifecycle state + notification ledger for AWS Marketplace.
--
-- Two changes, both idempotent:
--
-- 1) aws_marketplace_subscribers gains a lifecycle status driven by the SNS
--    subscription notifications, and loses its (customer_aws_account_id,
--    product_code) primary key. SaaS listings created on or after 2026-06-01
--    must support Concurrent Agreements — several simultaneous agreements on
--    one AWS account for the same product — so a single row per account and
--    product cannot represent the truth. Rows are now keyed by a surrogate id
--    and made unique per agreement via license_arn.
--
-- 2) aws_marketplace_notifications records every consumed SNS message. The
--    primary key on sns_message_id makes SQS at-least-once delivery idempotent.
--    matched=false retains events that cannot be correlated to a subscriber
--    instead of dropping them; /aws/fulfillment replays them when the matching
--    subscriber row appears later.

BEGIN;

ALTER TABLE aws_marketplace_subscribers
    ADD COLUMN IF NOT EXISTS subscription_status TEXT NOT NULL DEFAULT 'pending',
    ADD COLUMN IF NOT EXISTS status_updated_at   TIMESTAMPTZ;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'aws_marketplace_subscribers_status_chk') THEN
        ALTER TABLE aws_marketplace_subscribers
            ADD CONSTRAINT aws_marketplace_subscribers_status_chk
            CHECK (subscription_status IN
                   ('pending', 'active', 'cancelling', 'cancelled', 'failed'));
    END IF;
END $$;

-- Surrogate key. Adding an identity column backfills existing rows, so the
-- primary key swap below is safe on a populated table.
ALTER TABLE aws_marketplace_subscribers
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE aws_marketplace_subscribers
    DROP CONSTRAINT IF EXISTS aws_marketplace_subscribers_pkey;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'aws_marketplace_subscribers_pkey') THEN
        ALTER TABLE aws_marketplace_subscribers
            ADD CONSTRAINT aws_marketplace_subscribers_pkey PRIMARY KEY (id);
    END IF;
END $$;

-- One row per agreement. license_arn is the agreement discriminator; it is
-- NULL on integrations that predate LicenseArn, and COALESCE keeps exactly one
-- row in that case. This expression is the ON CONFLICT target in the handler.
CREATE UNIQUE INDEX IF NOT EXISTS aws_mp_subscribers_agreement_uq
    ON aws_marketplace_subscribers
       (customer_aws_account_id, product_code, COALESCE(license_arn, ''));

-- Join key for the notification consumer. Deliberately NOT unique: with
-- concurrent agreements the same customer_identifier can appear on several
-- rows, and the notification body carries no agreement discriminator.
CREATE INDEX IF NOT EXISTS aws_mp_subscribers_cust_ident_idx
    ON aws_marketplace_subscribers (customer_identifier, product_code)
    WHERE customer_identifier IS NOT NULL;

CREATE TABLE IF NOT EXISTS aws_marketplace_notifications (
    sns_message_id      TEXT PRIMARY KEY,
    action              TEXT NOT NULL,
    customer_identifier TEXT,
    product_code        TEXT,
    offer_identifier    TEXT,
    is_free_trial       BOOLEAN,
    sns_timestamp       TIMESTAMPTZ,
    received_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    matched             BOOLEAN NOT NULL DEFAULT FALSE,
    matched_rows        INTEGER NOT NULL DEFAULT 0,
    raw                 JSONB NOT NULL
);

-- Lookup for the replay path in /aws/fulfillment.
CREATE INDEX IF NOT EXISTS aws_mp_notifications_unmatched_idx
    ON aws_marketplace_notifications (customer_identifier, product_code)
    WHERE NOT matched;

COMMIT;
