"""MolTrust Scout Agent - Trend Detection for the Agent Economy"""

import os, json, datetime, httpx, time

AGENT_DID = "did:moltrust:28a0984ab85d4c40"
AGENT_NAME = "MolTrust Scout"
API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
LOG_DIR = os.path.expanduser("~/moltstack/logs")

SEARCH_TOPICS = [
    "agent economy trust layer 2026",
    "ERC-8004 trustless agents",
    "AI agent identity verification DID",
    "agentic commerce payments x402",
    "AI agent reputation system",
]


def search_web(query):
    try:
        resp = httpx.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-haiku-4-5-20251001",
                "max_tokens": 1000,
                "tools": [{"type": "web_search_20250305", "name": "web_search"}],
                "messages": [{"role": "user", "content": f"Search for latest news about: {query}. Focus on last 7 days. Brief summary only."}],
            },
            timeout=30.0,
        )
        if resp.status_code == 200:
            data = resp.json()
            return [b["text"] for b in data.get("content", []) if b.get("type") == "text"]
        return [f"Search error: {resp.status_code}"]
    except Exception as e:
        return [f"Search failed: {e}"]


def generate_briefing(findings):
    prompt = f"""You are the MolTrust Scout Agent (DID: {AGENT_DID}).
Produce a concise intelligence briefing for the MolTrust team.

MolTrust is a trust layer API for the agent economy: W3C DID:web identity, Verifiable Credentials (Ed25519), reputation scoring, Lightning payments, GitHub OAuth.

Search findings:

"""
    for topic, results in findings.items():
        prompt += f"\n## {topic}\n"
        for r in results:
            prompt += f"{r}\n"

    prompt += """

Briefing format:
1. TOP TRENDS - What's moving in the agent economy?
2. OPPORTUNITIES - What can MolTrust capitalize on?
3. THREATS - Competitors or standards to watch?
4. ACTION ITEMS - What should we do this week?

Be concise and actionable."""

    try:
        resp = httpx.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key": API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json",
            },
            json={
                "model": "claude-haiku-4-5-20251001",
                "max_tokens": 2000,
                "messages": [{"role": "user", "content": prompt}],
            },
            timeout=60.0,
        )
        if resp.status_code == 200:
            data = resp.json()
            return "\n".join(b["text"] for b in data.get("content", []) if b.get("type") == "text")
        return f"Briefing failed: {resp.status_code}"
    except Exception as e:
        return f"Briefing failed: {e}"


def run():
    now = datetime.datetime.now(datetime.UTC)
    print(f"\n{'='*60}")
    print(f"MOLTRUST SCOUT AGENT")
    print(f"DID: {AGENT_DID}")
    print(f"Time: {now.strftime('%Y-%m-%d %H:%M UTC')}")
    print(f"{'='*60}\n")

    if not API_KEY:
        print("ERROR: ANTHROPIC_API_KEY not set")
        return

    print("Phase 1: Scanning trends...\n")
    findings = {}
    for topic in SEARCH_TOPICS:
        print(f"  Searching: {topic}...")
        results = search_web(topic)
        findings[topic] = results
        time.sleep(5)

    print("\nPhase 2: Generating briefing...\n")
    time.sleep(5)
    briefing = generate_briefing(findings)

    date_str = now.strftime("%Y%m%d_%H%M")
    report_path = os.path.join(LOG_DIR, f"scout_{date_str}.md")

    report = f"""# MolTrust Scout Briefing
**Date:** {now.strftime('%Y-%m-%d %H:%M UTC')}
**Agent:** {AGENT_NAME} ({AGENT_DID})

---

{briefing}

---

*Generated by MolTrust Scout Agent*
"""
    with open(report_path, "w") as f:
        f.write(report)

    print(briefing)
    print(f"\nReport saved: {report_path}")


if __name__ == "__main__":
    run()
